# frozen_string_literal: true

# Generated by `bin/rails generate karst:install`.
#
# Karst's access sweep and "Test as" workflow drive a completely isolated
# ActionDispatch::Integration::Session per probed principal (see
# config.assume_identity / config.clear_identity in
# config/initializers/karst.rb) -- never the real browser session. That
# probe session cannot call this application's real sign-in flow directly:
# Karst does not know this application's password scheme, token model, or
# whether it uses Devise, Warden, has_secure_password, or something else
# entirely.
#
# Instead, the configured `assume_identity` hook makes a real HTTP request
# into this application (POST /karst_test_login, wired in config/routes.rb
# by this generator) so this controller can run inside the normal
# request/response cycle and establish authentication using this
# application's own real code -- not a guess made on its behalf.
#
# This controller is development-only in effect:
#   - config/routes.rb only draws its routes inside `if Rails.env.development?`
#   - do not remove that guard, and do not mount these routes in any other
#     environment
#   - the TODOs below must only ever establish/clear a session; never read,
#     log, or return a real password, external token, or other secret
#
# Karst never constantizes an arbitrary model name from the request.
# `resolve_principal` below never calls `find`, `constantize`, or any other
# unrestricted lookup on the submitted params -- it only ever returns a
# principal already yielded by this application's own configured
# `config.principals`, resolved strictly through `Karst::Identity.resolve`.
# Do not replace it with a direct `Model.find(params[:principal_id])`: that
# would let a submitted id reach outside the principal scope this
# application configured, exactly what `config.principals` exists to bound.
class KarstIdentityController < ApplicationController
  # This is an internal, development-only probe endpoint invoked by Karst's
  # own integration session -- not a user-facing form a third-party page
  # could forge a request against. Skip forgery protection defensively
  # (raise: false) so this works whether or not ApplicationController
  # defines the verify_authenticity_token callback at all.
  skip_before_action :verify_authenticity_token, raise: false

  # TODO: if ApplicationController requires authentication for every action
  # by default, this endpoint needs to be reachable *before* that identity
  # is established. Skip that filter here too, defensively, e.g.:
  #
  #   skip_before_action :authenticate_user!, raise: false

  def create
    principal = resolve_principal
    return head(:forbidden) unless principal

    # TODO: replace with this application's real authentication setup,
    # using the already-resolved `principal` above -- never re-derive it
    # from params. Whatever happens here must be fully undone by `destroy`
    # below, and must be safe to call many times in a row: a single access
    # sweep probes many principals, each wrapped in its own
    # assume/run/clear cycle.
    #
    # Examples -- do not assume any of these match this application; pick
    # the one that fits, or write something else entirely:
    #
    #   # Rails session-based auth:
    #   session[:user_id] = principal.id
    #
    #   # Devise:
    #   sign_in(principal)
    #
    #   # Warden directly:
    #   request.env["warden"].set_user(principal)
    raise NotImplementedError, "KarstIdentityController#create has not been configured for this application yet"
  end

  # TODO: replace with this application's real sign-out/session-clearing
  # code -- the exact inverse of whatever `create` above does.
  #
  #   # Rails session-based auth:
  #   session.delete(:user_id)
  #
  #   # Devise:
  #   sign_out(:user)
  def destroy
    raise NotImplementedError, "KarstIdentityController#destroy has not been configured for this application yet"
  end

  private

  # Resolves params[:principal_id] strictly within this application's own
  # config.principals, mirroring how Karst's browser "Test as" flow already
  # resolves a submitted principal -- never an unrestricted model lookup.
  def resolve_principal
    Karst::Identity.resolve(model_name: params[:principal_type], id: params[:principal_id])
  end
end
