# frozen_string_literal: true

# Generated by `bin/rails generate karst:install`.
#
# Karst's access sweep and "Test as" workflow drive a completely isolated
# ActionDispatch::Integration::Session per probed principal (see
# config.assume_identity / config.clear_identity in
# config/initializers/karst.rb) -- never the real browser session. That
# probe session cannot call this application's real sign-in flow directly:
# Karst does not know this application's password scheme, token model, or
# whether it uses Devise, Warden, has_secure_password, or something else
# entirely.
#
# Instead, the configured `assume_identity` hook makes a real HTTP request
# into this application (POST /karst_test_login, wired in config/routes.rb
# by this generator) so this controller can run inside the normal
# request/response cycle and establish authentication using this
# application's own real code -- not a guess made on its behalf.
#
# This controller is development-only in effect:
#   - config/routes.rb only draws its routes inside `if Rails.env.development?`
#   - do not remove that guard, and do not mount these routes in any other
#     environment
#   - the TODOs below must only ever establish/clear a session; never read,
#     log, or return a real password, external token, or other secret
#
# Karst never constantizes an arbitrary model name from the request:
# `params[:principal_id]` is only ever compared against principals already
# yielded by this application's own configured `config.principals`, resolved
# through Karst::Identity -- never used to look up an arbitrary record on
# its own.
class KarstIdentityController < ApplicationController
  # This is an internal, development-only probe endpoint invoked by Karst's
  # own integration session -- not a user-facing form a third-party page
  # could forge a request against. Skip forgery protection defensively
  # (raise: false) so this works whether or not ApplicationController
  # defines the verify_authenticity_token callback at all.
  skip_before_action :verify_authenticity_token, raise: false

  # TODO: if ApplicationController requires authentication for every action
  # by default, this endpoint needs to be reachable *before* that identity
  # is established. Skip that filter here too, defensively, e.g.:
  #
  #   skip_before_action :authenticate_user!, raise: false

  # TODO: replace with this application's real authentication setup.
  # Whatever happens here must be fully undone by `destroy` below, and must
  # be safe to call many times in a row: a single access sweep probes many
  # principals, each wrapped in its own assume/run/clear cycle.
  #
  # Examples -- do not assume any of these match this application; pick the
  # one that fits, or write something else entirely:
  #
  #   # Rails session-based auth:
  #   session[:user_id] = params[:principal_id]
  #
  #   # Devise:
  #   user = User.find(params[:principal_id])
  #   sign_in(user)
  #
  #   # Warden directly:
  #   request.env["warden"].set_user(User.find(params[:principal_id]))
  def create
    raise NotImplementedError, "KarstIdentityController#create has not been configured for this application yet"
  end

  # TODO: replace with this application's real sign-out/session-clearing
  # code -- the exact inverse of whatever `create` above does.
  #
  #   # Rails session-based auth:
  #   session.delete(:user_id)
  #
  #   # Devise:
  #   sign_out(:user)
  def destroy
    raise NotImplementedError, "KarstIdentityController#destroy has not been configured for this application yet"
  end
end
