# frozen_string_literal: true

# Generated by `bin/rails generate karst:install`.
#
# Karst does not know how this application authenticates, which model (if
# any) represents a principal, or which principals are safe to expose to
# local development tooling. Every hook below is commented out on purpose:
# uncomment and adapt the ones you want, or write your own. The examples
# shown are examples, not assumptions Karst makes about this application.
#
# See app/controllers/karst_identity_controller.rb (generated alongside this
# file) for the development-only endpoint the probe hooks below can drive.
Karst.configure do |config|
  # ---------------------------------------------------------------------
  # config.principals
  # ---------------------------------------------------------------------
  # The allowed principal universe: everything Karst may offer for an
  # access sweep or a "Test as" button in the /karst panel. Karst never
  # enumerates, samples, or materializes this on its own; it is only
  # evaluated when a developer explicitly triggers one of those actions.
  # Scope it to whatever you are comfortable exposing to local development
  # tooling -- for example, excluding staff/admin accounts, or scoping to a
  # seeded development dataset.
  #
  # config.principals = -> { User.all }

  # ---------------------------------------------------------------------
  # config.principal_dimensions (optional)
  # ---------------------------------------------------------------------
  # Coarse, non-PII observed states worth deliberately representing while
  # sampling -- not an authorization claim. Karst may report
  # `role=local_admin`; it never claims that state grants access. Supports
  # a plain attribute, a boolean predicate, or a callable evaluated over an
  # already-bounded candidate pool. A dimension named (or reading an
  # attribute named) like email/name/phone/token/password is rejected --
  # Karst dimensions are for coarse state, not user identity data.
  #
  # config.principal_dimensions = {
  #   role: :role,
  #   system_admin: :system_admin?,
  #   premium: ->(user) { user.premium? }
  # }

  # ---------------------------------------------------------------------
  # config.principal_populations (optional)
  # ---------------------------------------------------------------------
  # Application-authored candidate populations for the model config.principals
  # resolves to -- a Hash of name => zero-argument callable, each expected
  # to return an ActiveRecord::Relation scoped to that same model, for
  # example a named scope such as `scope :system_admins, -> { where(is_admin:
  # true) }`. This only tells Karst "these records are worth trying"; it
  # never implies that a population grants access or explains any observed
  # outcome. Karst does not verify that a callable came from Rails' own
  # `scope` macro specifically -- only that calling it returns a same-model
  # relation -- and a callable that raises, requires an argument, or
  # returns something else is skipped rather than raised.
  #
  # config.principal_populations = {
  #   system_admins: -> { User.system_admins },
  #   auditors: -> { User.auditors },
  #   responders: -> { User.responders }
  # }

  # ---------------------------------------------------------------------
  # config.principal_sources (optional, for more than one principal model)
  # ---------------------------------------------------------------------
  # Only needed when this application represents identity as more than one
  # model (e.g. Author and Reader) instead of a single config.principals.
  # Each source is sampled and resolved independently -- Karst never merges
  # them into one combined dataset -- and may declare its own dimensions
  # and populations.
  #
  # config.principal_sources = {
  #   authors: { records: -> { Author.all }, dimensions: { premium: :premium? },
  #              populations: { admins: -> { Author.admins } } },
  #   readers: -> { Reader.all }
  # }

  # ---------------------------------------------------------------------
  # config.assume_identity / config.clear_identity
  # ---------------------------------------------------------------------
  # Operate on an isolated ActionDispatch::Integration::Session that Karst
  # creates and discards per probed principal -- never the real browser
  # session. `assume_identity` receives that session and one principal
  # yielded by config.principals; `clear_identity` receives only the
  # session. Both must be configured together.
  #
  # The example below drives the development-only route/controller this
  # generator also created (config/routes.rb, KarstIdentityController). You
  # are not required to use them: any mechanism that establishes and tears
  # down authentication on an ActionDispatch::Integration::Session works,
  # including calling Warden's public API directly on the session.
  #
  # Sends both principal_type and principal_id so the controller can
  # resolve the principal strictly through Karst::Identity.resolve, the
  # same descriptor Karst itself derives via Karst::Identity.describe --
  # never a bare id a controller might otherwise be tempted to pass
  # straight into Model.find.
  #
  # config.assume_identity = lambda do |session, principal|
  #   descriptor = Karst::Identity.describe(principal)
  #   session.post "/karst_test_login", params: {
  #     principal_type: descriptor.model_name,
  #     principal_id: descriptor.id
  #   }
  # end
  #
  # config.clear_identity = lambda do |session|
  #   session.delete "/karst_test_logout"
  # end

  # ---------------------------------------------------------------------
  # config.assume_browser_identity / config.clear_browser_identity
  # ---------------------------------------------------------------------
  # Operate on the *real* current Rack request/session -- not the isolated
  # probe session above -- to power the "Test as" button in the /karst
  # panel for manual QA. These must mirror this application's real
  # authentication/session semantics exactly: they mutate the session a
  # real developer is about to browse with, and getting them wrong can
  # leave that session in a broken or inconsistent auth state.
  #
  # Example only -- replace `:user_id` with whatever this application's own
  # session-based authentication actually keys on:
  #
  # config.assume_browser_identity = lambda do |request, principal|
  #   request.session[:user_id] = principal.id
  # end
  #
  # config.clear_browser_identity = lambda do |request|
  #   request.session.delete(:user_id)
  # end

  # ---------------------------------------------------------------------
  # config.principal_label (optional)
  # ---------------------------------------------------------------------
  # Only evaluated when a human-readable descriptor is requested. Defaults
  # to a safe "ModelName #id" form and never calls #to_s or reads arbitrary
  # attributes unless configured.
  #
  # config.principal_label = ->(principal) { "#{principal.class.name} ##{principal.id}" }

  # ---------------------------------------------------------------------
  # Future work
  # ---------------------------------------------------------------------
  # Karst does not detect or wire up Devise, Warden, or any other
  # authentication library automatically -- doing so safely for an
  # arbitrary application is out of scope for this generator. A future
  # `karst:install --devise` (or similar) may offer an alternate default
  # for the hooks above; until then, the placeholders are the whole
  # contract.
end
