# frozen_string_literal: true

# Generated by `bin/rails generate karst:install`.
#
# ---------------------------------------------------------------------------
# The golden path: a conventional single-model Devise application
# ---------------------------------------------------------------------------
# If this application uses Devise with exactly one Devise-authenticatable
# model (commonly `User`), Karst needs none of the configuration below.
# It detects that model and its Warden scope from Devise's own routing
# metadata (Devise.mappings, populated by `devise_for` in config/routes.rb)
# and uses Warden's public `set_user`/`logout` API for access-sweep probes
# and browser "Test as" -- no identity lambdas required. Leave this file
# exactly as generated and start Rails.
#
# Karst never guesses: if it finds more than one Devise model, or none at
# all, it says so on the /karst panel instead of picking one for you.
Karst.configure do |config|
  # ---------------------------------------------------------------------
  # If Karst cannot determine your principal model automatically --
  # multiple Devise models, or none -- configure it explicitly. Karst will
  # still use Warden automatically for probe/browser identity as long as it
  # can determine the Devise scope for whatever this returns (see
  # DeviseSupport in README.md#identity-adapters).
  # ---------------------------------------------------------------------
  #
  # config.principals = -> { User.all }
  # config.principals = -> { Admin.all }

  # ---------------------------------------------------------------------
  # config.principal_populations (optional)
  # ---------------------------------------------------------------------
  # Application-authored candidate populations for the model config.principals
  # resolves to -- a Hash of name => zero-argument callable, each expected
  # to return an ActiveRecord::Relation scoped to that same model, for
  # example a named scope such as `scope :system_admins, -> { where(is_admin:
  # true) }`. This only tells Karst "these records are worth trying"; it
  # never implies that a population grants access or explains any observed
  # outcome. Karst does not verify that a callable came from Rails' own
  # `scope` macro specifically -- only that calling it returns a same-model
  # relation -- and a callable that raises, requires an argument, or
  # returns something else is skipped rather than raised.
  #
  # Approved populations are retried automatically: if the ordinary sample
  # finds no usable user, Karst tries each of these in the order written
  # here and stops at the first one that produces a usable outcome. Only
  # populations configured here (or on a config.principal_sources entry)
  # are ever executed automatically -- a name merely discovered at
  # /karst/populations never is. At most config.population_retry_limit
  # records per population (default 3), and at most
  # config.access_sweep_limit extra requests in total.
  #
  # config.principal_populations = {
  #   system_admins: -> { User.system_admins },
  #   auditors: -> { User.auditors },
  #   responders: -> { User.responders }
  # }

  # ---------------------------------------------------------------------
  # config.principal_sources (optional, for more than one principal model)
  # ---------------------------------------------------------------------
  # Only needed when this application represents identity as more than one
  # model (e.g. Author and Reader) instead of a single config.principals.
  # Each source is sampled and resolved independently -- Karst never merges
  # them into one combined dataset -- and may declare its own populations.
  # Karst still infers Warden probe/browser identity per principal from
  # Devise's own mapping for whichever source model produced it, as long as
  # exactly one source is configured (see README.md#identity-adapters).
  #
  # config.principal_sources = {
  #   authors: { records: -> { Author.all },
  #              populations: { admins: -> { Author.admins } } },
  #   readers: -> { Reader.all }
  # }

  # ---------------------------------------------------------------------
  # Custom/non-Devise authentication
  # ---------------------------------------------------------------------
  # Applications not on the Devise/Warden golden path above configure every
  # hook by hand. See app/controllers/karst_identity_controller.rb
  # (generated alongside this file) for the development-only endpoint the
  # probe hooks below can drive.
  #
  # config.assume_identity / config.clear_identity
  #   Operate on an isolated ActionDispatch::Integration::Session that Karst
  #   creates and discards per probed principal -- never the real browser
  #   session. `assume_identity` receives that session and one principal
  #   yielded by config.principals; `clear_identity` receives only the
  #   session. Both must be configured together.
  #
  #   Sends both principal_type and principal_id so the controller can
  #   resolve the principal strictly through Karst::Identity.resolve, the
  #   same descriptor Karst itself derives via Karst::Identity.describe --
  #   never a bare id a controller might otherwise be tempted to pass
  #   straight into Model.find.
  #
  # config.assume_identity = lambda do |session, principal|
  #   descriptor = Karst::Identity.describe(principal)
  #   session.post "/karst_test_login", params: {
  #     principal_type: descriptor.model_name,
  #     principal_id: descriptor.id
  #   }
  # end
  #
  # config.clear_identity = lambda do |session|
  #   session.delete "/karst_test_logout"
  # end

  # config.assume_browser_identity / config.clear_browser_identity
  #   Operate on the *real* current Rack request/session -- not the isolated
  #   probe session above -- to power the "Test as" button in the /karst
  #   panel for manual QA. These must mirror this application's real
  #   authentication/session semantics exactly: they mutate the session a
  #   real developer is about to browse with, and getting them wrong can
  #   leave that session in a broken or inconsistent auth state.
  #
  #   Example only -- replace `:user_id` with whatever this application's
  #   own session-based authentication actually keys on:
  #
  # config.assume_browser_identity = lambda do |request, principal|
  #   request.session[:user_id] = principal.id
  # end
  #
  # config.clear_browser_identity = lambda do |request|
  #   request.session.delete(:user_id)
  # end

  # ---------------------------------------------------------------------
  # config.principal_label (optional)
  # ---------------------------------------------------------------------
  # Only evaluated when a human-readable descriptor is requested. Defaults
  # to a safe "ModelName #id" form and never calls #to_s or reads arbitrary
  # attributes unless configured.
  #
  # config.principal_label = ->(principal) { "#{principal.class.name} ##{principal.id}" }
end
